name: News Headlines

on:
  schedule:
    # This cron job runs every day at 13:00 UTC (18:00 PKT)
    - cron: '0 13 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow
  
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          pip install tweepy beautifulsoup4 requests

      - name: Run News Headlines
        run: |
          python news_headlines.py  # Replace with the name of your script
        env:
          CONSUMER_KEY: ${{ secrets.consumer_key }}
          CONSUMER_SECRET_KEY: ${{ secrets.consumer_secret_key }}
          ACCESS_TOKEN: ${{ secrets.access_token }}
          ACCESS_TOKEN_SECRET: ${{ secrets.access_token_secret }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f unique_counter.txt ]; then
            git add unique_counter.txt
            git commit -m "Update counter"
            git push origin main
          fi
